require:
  - standard
  - rubocop-rspec

inherit_gem:
  rubocop-config-prettier: config/rubocop.yml
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - node_modules/**/*

Layout/LineLength:
  Max: 120
